// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PharmacyStore_Repository.Models;

public partial class MedicineInformation
{
    public string MedicineId { get; set; }

    public string MedicineName { get; set; }

    public string ActiveIngredients { get; set; }

    public string ExpirationDate { get; set; }

    public string DosageForm { get; set; }

    public string WarningsAndPrecautions { get; set; }

    public string ManufacturerId { get; set; }

    public virtual Manufacturer Manufacturer { get; set; }
}