// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PharmacyStore_Repository.Models;

public partial class StoreAccount
{
    public int StoreAccountId { get; set; }

    public string StoreAccountPassword { get; set; }

    public string EmailAddress { get; set; }

    public string StoreAccountDescription { get; set; }

    public int? Role { get; set; }
}