// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace LionPetManagement_Repositories_DoanNgocTrung.Models;

public partial class LionProfile
{

    public int LionProfileId { get; set; }
    [Required(ErrorMessage = "Please select a Lion Type.")]
    [Range(1, int.MaxValue, ErrorMessage = "Please select a Lion Type.")]
    public int LionTypeId { get; set; }

    [Required(ErrorMessage = "LionName is required.")]
    [MinLength(4, ErrorMessage = "LionName must be at least 4 characters.")]
    [RegularExpression(@"^[A-Z][a-zA-Z0-9]*(\s[A-Z][a-zA-Z0-9]*)*$", ErrorMessage = "Each word must start with capital letter, No special characters allowed (#, @, &, (, )).")]
    public string LionName { get; set; }

    [Required(ErrorMessage = "Weight is required.")]
    [Range(31, int.MaxValue, ErrorMessage = "Weight must be greater than 30.")]
    public double Weight { get; set; }
   
    [Required(ErrorMessage = "Characteristics is required.")]
    public string Characteristics { get; set; }
   
    [Required(ErrorMessage = "Warning is required.")]

    public string Warning { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual LionType LionType { get; set; }
}

