// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

[Table("LionType")]
public partial class LionType
{
    [Key]
    public int LionTypeId { get; set; }

    [StringLength(250)]
    public string LionTypeName { get; set; }

    [StringLength(250)]
    public string Origin { get; set; }

    [StringLength(1000)]
    public string Description { get; set; }

    [InverseProperty("LionType")]
    public virtual ICollection<LionProfile> LionProfiles { get; set; } = new List<LionProfile>();
}