// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Repositories.Validations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repositories.Models;

[Table("LionProfile")]
public partial class LionProfile
{
    [Key]
    [Required]/////
    public int LionProfileId { get; set; }

    [Required]
    public int LionTypeId { get; set; }

    [Required]
    [StringLength(150)]
    [MinLength(4, ErrorMessage = "LionName must be at least 4 characters long.")]
    [RegularExpression(@"^(?!.*[#@&()])([A-Z][a-zA-Z]*\s*)+$", ErrorMessage = "Each word must start with a capital letter and contain only letters. No special characters allowed.")]

    public string LionName { get; set; }

    [Required]
    //[Range(30, double.MaxValue, ErrorMessage = "Weight must be greater than 30.")]
    [GreaterThan30Attribute(ErrorMessage = "Weight must be greater than 30.")]
    public double Weight { get; set; }

    [Required]
    [StringLength(2000)]
    public string Characteristics { get; set; }

    [Required]
    [StringLength(1500)]
    public string Warning { get; set; }

    [Required]

    [Column(TypeName = "datetime")]
    public DateTime ModifiedDate { get; set; }

    [ForeignKey("LionTypeId")]
    [InverseProperty("LionProfiles")]
    public virtual LionType LionType { get; set; }
}