// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

[Table("LionAccount")]
public partial class LionAccount
{
    [Key]
    public int AccountID { get; set; }

    [Required]
    [StringLength(50)]
    public string UserName { get; set; }

    [StringLength(100)]
    public string Password { get; set; }

    [Required]
    [StringLength(100)]
    public string FullName { get; set; }

    [Required]
    [StringLength(150)]
    public string Email { get; set; }

    [Required]
    [StringLength(50)]
    public string Phone { get; set; }

    public int RoleId { get; set; }
}