// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PharmaceuticalManagement_Repository.Models;

public partial class MedicineInformation
{
    [Required(ErrorMessage = "Medicine Id is required.")]
    public string MedicineId { get; set; }

    [Required(ErrorMessage = "Medicine Name is required.")]
    public string MedicineName { get; set; }
    
    [MinLength(10)]
    [RegularExpression(@"^[A-Z][a-zA-Z0-9]*(\s[A-Z][a-zA-Z0-9]*)*$", ErrorMessage = "Each word must start with capital letter, No special characters allowed (#, @, &, (, )).")]
    public string ActiveIngredients { get; set; }

    [Required(ErrorMessage = "Expiration Date is required.")]
    public string ExpirationDate { get; set; }

    [Required(ErrorMessage = "DosageForm is required.")]
    public string DosageForm { get; set; }

    [Required(ErrorMessage = "Warnings And Precautions is required.")]
    public string WarningsAndPrecautions { get; set; }
    public string ManufacturerId { get; set; }

    public virtual Manufacturer Manufacturer { get; set; }
}